spring:
  application:
    name: user-service
  profiles:
    active: users, micro
  config:
    import: configserver:http://localhost:8888
server:
  port: 0

jwt:
  secret: secret
  lifetime: 360000000
