spring:
  application:
    name: user-service
  profiles:
    active: users, micro
  config:
    import: configserver:http://localhost:8888
server:
  port: 0

springdoc:
  swagger-ui:
    config-url: /user-service/v3/api-docs/swagger-config
    url: /user-service/v3/api-docs
