spring:
    application:
        name: order-service
    profiles:
        active: order, micro, rabbit
    config:
        import: configserver:http://localhost:8888
server:
    port: 0

springdoc:
    swagger-ui:
        config-url: /order-service/v3/api-docs/swagger-config
        url: /order-service/v3/api-docs
