spring:
  application:
    name: cart-service
  profiles:
    active: cart, micro, rabbit
  config:
    import: configserver:http://localhost:8888


server:
  port: 0

springdoc:
  swagger-ui:
    config-url: /cart-service/v3/api-docs/swagger-config
    url: /cart-service/v3/api-docs


