server:
  port: 8765
spring:
  config:
    import: configserver:http://localhost:8888
  application:
    name: shop-gateway

logging:
  level:
    org:
      springframework:
        cloud:
          gateway: info

jwt:
  secret: secretdsadsadsadsadsadsadsadsadasdsadasdsadasdsadddddddddddddddddddddd
  lifetime: 360000000