eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8765
spring:
  application:
    name: shop-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true