spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/shop-products
    username: postgres
    password: 9567

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  application:
    name: item-service

eureka:
  client:
    service-url:
      defaultZone:
        http://localhost:8761/eureka
server:
  port: 0
