server:
  port: 8888
spring:
  application:
    name: shop-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Wolroys/shop-configuration.git
          clone-on-start: true
          basedir: file://C:/Users/averg/Desktop/shop-app-config
          username: Wolroys
          password: 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
          default-label: master